// generated by scripts/new-page.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/helloworld.mdx";
import ssgConfig from "../mdxx-ssg.json";
import { Layout, Article } from "mdxx-ssg-components";

export const config = {
  amp: true,
};

export default () => (
  <Layout ssgConfig={ssgConfig}>
    <Article ssgConfig={ssgConfig} title={frontmatter.title}>
      <Doc amp />
    </Article>
  </Layout>
);
