// generated by scripts/new-page.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/mdxx-introduction.mdx";
import { ItemLayout } from "../components/ItemLayout";
import ssgConfig from "../mdxx-ssg.json";

const newProps = {...ssgConfig, ...frontmatter} as any;

export const config = {
  amp: true,
};

export default () => (
  <ItemLayout {...newProps}>
    <Doc amp />
  </ItemLayout>
);
